version: '3.8'

services:
  angular:
    build:
      context: ./front   # chemin vers ton projet Angular
      dockerfile: Dockerfile
    image: angular16_app
    ports:
      - "4200:80"
    networks:
      - app-network
    restart: always

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passer
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
