version: '3.8'

services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    image: angular16_app
    ports:
      - "4200:80"   # Angular dispo sur http://localhost:4200
    restart: always

